name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Укажите нужную версию Python

    - name: Build with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile --debug=all sketh_gui.py  # Добавлено --debug=all для отладки

    - name: List files in dist directory
      run: |
        if [ ${{ runner.os }} == 'Windows' ]; then dir dist; else ls dist; fi  # Проверка содержимого папки dist

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sketh-gui-${{ matrix.os }}
        path: |
          dist/sketh_gui.exe  # Для Windows
          dist/sketh_gui      # Для других ОС
