name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-10.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Укажите нужную версию Python

    - name: Build with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile sketh_gui.py  # Замените на имя вашего скрипта

    - name: List files in dist directory
      run: ls dist  # Проверка содержимого папки dist

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4  # Обновлено до v4
      with:
        name: sketh-gui-${{ matrix.os }}
        path: dist/sketh_gui  # Убедитесь, что это имя вашего исполняемого файла
