name: Build and Release

on:
  workflow_dispatch:  # Позволяет запускать workflow вручную через интерфейс

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Upgrade pip
      run: python -m pip install --upgrade --no-deps pip

    - name: Build with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile sketh_gui.py

    - name: List files in dist directory
      run: |
        if [ ${{ runner.os }} == 'Windows' ]; then dir dist; else ls dist; fi

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sketh_gui-artifact-${{ github.run_id }}  # Уникальное имя артефакта
        path: |
          dist/sketh_gui.exe  # Для Windows
          dist/sketh_gui      # Для других ОС

